import { Inter } from "next/font/google";
import "./globals.css";
import { Fjalla_One} from "next/font/google";


const Bebas = Fjalla_One({
  subsets: ['latin'],
 
  variable: '--font-Bebas_Neue',
  weight: ['400']
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Bebas.variable}`}>{children}</body>
    </html>
  );
}
